### ISSUE TITLE
Request: Better documentation around using Browserfy for importing javascript

### ISSUE THREAD

**Issue by bwhittington** [fbrctr/fabricator#101]
Documentation I would like to see to make it easier for newcomers to get acquainted with Fabricator.
1) How to import external libraries 
2) How to use imported modules in other modules.

I spent about 2 hours to do trying to import jQuery and I am not sure I did this correctly. To get this to work for me, I had to put the jQuery library in the same folder as my toolkit.js file and then put var $ = require('./jquery-2.1.3.min.js'); But jQuery still isn't work in my other modules for a component.

I'll add other stuff I as I run into it.  I've been working with Fabricator for my own learning and I am really seeing a lot of uses for it.  Just trying to help let you know where sticky points are for people who don't have people actively using it sitting next to them.  I first looked at in August and installation was kind of pain then but this time around it was much easier.

**Comment by LukeAskew** [comment]
:+1: 

I'll make a point to flesh this out more.

In the meantime, you can check out some of the "recipes". They are not comprehensive, but should get you going the right direction.

https://github.com/resource/fabricator/tree/master/recipes

**Comment by bwhittington** [comment]
Thanks for responding.  I was able to get something working without dealing with the recipes. I'm not sure what long term implications of doing it this are but here is an example of my toolkit.js

var $ = require('./jquery-2.1.3.min.js');

var header = require("./components/header.js");
header.openSearchBox($);
header.closeSearchBox($);

Basically, if I want to use jquery in all of my component JS libraries, I have to pass it in to the methods. Any feedback on that?

**Comment by LukeAskew** [comment]
That seems like a reasonable approach. There's a couple of approaches you can take here.

1. Include jQuery as a module (Browserify) like you're demostrating. I like this approach because explicit module inclusions make app a little more clear IMO. The only suggestion I have is to install jquery using `npm` so that it downloads to `node_modules`. This allows you to include it like `var $ = ('jquery');` and keeps you from having to include the file in version control.
2. Follow the recipe and use Bower to manage jQuery and add the file to a `vendor` task so that `$` is an implied global.

**Comment by LukeAskew** [comment]
http://fbrctr.github.io/advanced/third-party.html
