### ISSUE TITLE
Custom-plugin: other Precompilers

### ISSUE THREAD

**Issue by VinSpee** [fbrctr/fabricator#108]
Hi! Creator of http://vinspee.me/style-guide-guide here.

I'm really interested in using fabricator for my next project. I'm one of the strange (and growing) among us that doesn't use Sass — I use a custom PostCSS build. I have a [gulp task for it](https://gist.github.com/VinSpee/f78e07b8ef4e3d4c9d2b) that works great. I'd love the option to override the default fabricator styles task with my own - is that possible?

Thanks! The new site looks great.

**Comment by LukeAskew** [comment]
Yup. Sure is. You would just modify the `gulpfile.js` to use the new task and change the `toolkit.scss` file extension to whatever PostCSS likes.

This is why I use the folder name `styles` instead of `scss` or `sass` - it makes swapping a little easier.

I will make sure to document this customization in the new docs.

**Comment by VinSpee** [comment]
Awesome - it would be cool to have this as a configuration option in the generator. Thanks!

**Comment by LukeAskew** [comment]
Noted. I'm not familiar with PostCSS. Once the generator is updated to 1.0 (later this week), a PR for that feature would be welcomed.

**Comment by VinSpee** [comment]
Will do! Thanks.

**Comment by LukeAskew** [comment]
Hey @VinSpee the generator has been updated, but I'm not totally sure how to integrate this type of configuration since fabricator is just included as a submodule. Open to ideas.

https://github.com/fbrctr/generator-fabricator
