### ISSUE TITLE
More information on making a more complex html structure

### ISSUE THREAD

**Issue by herince** [fbrctr/fabricator#121]
Could you please add more info about what I should change to make a more complex html folder structure in src?

Until now I was using the basic structure. Then I tried to split my components into folders ( moved the buttons into a 'buttons' folder, which is still inside 'components'). It didn't work by default.. I tried changing paths in the gulpfile. Still - no success. Then I looked at the generated data.json file and I saw that there was json for the folder 'buttons' but no json for the files in it.

I may have missed something simple. Help me Obi-One Kenobi, you're my only hope!

**Comment by LukeAskew** [comment]
What version are you running? If your instance in generating a data.json file, then your pre 1.0.

Grouped materials came in 1.0

**Comment by herince** [comment]
It was 0.7.0. Just updated it. Now I'm trying to figure out how does the new one work (with the hlep of the docs)... the links in the menu for my components do not compile correctly (and I just added custom html files in the components and structures folders). So I keep getting the same mistake "Cannot GET /src/materials/components.html"... *still reading and trying to find where my mistake is*

**Comment by LukeAskew** [comment]
Apologies on the lack of documentation; been trying to improve it. Hopefully I can be some help here.

"Materials" are just partials that can be used when templating a page. They are not compiled or viewable on their own served pages. They are only used as partials. e.g. `{{> material-name}}`.

The pages Fabricator actually generates and serves up are in `src/views` or in `src/views/sub-dir`. By default, Fabricator puts the toolkit doc/style guide pages in root so that http://localhost:3000 opens up to your toolkit homepage. However, you don't have to keep it that way. You can organize your views however you want. They are all templated using the same context (outlined [here](http://fbrctr.github.io/building-a-toolkit/data.html) under "Context") so you can just construct views and call them whatever you want. Checkout the [fbrctr.github.io source](https://github.com/fbrctr/fbrctr.github.io/tree/fabricator/src/views) as an example.

The default template for the side menu is also pretty basic. It just iterated over the `materials` object in the page context and adds a list group https://github.com/fbrctr/fabricator/blob/95f4cf42292744c4a7e1767e65616afe62b891e5/src/views/layouts/includes/f-menu.html#L12.

You could change this to be more granular. I am currently doing something like this on a project:

```
<li>
	<a href="elements.html" class="f-menu__heading">Elements</a>
	<ul>
		{{#each materials.elements.items}}
		<li>
			<a href="elements.html#{{@key}}">{{name}}</a>
		</li>
		{{/each}}
	</ul>
</li>

<li>
	<a href="components.html" class="f-menu__heading">Components</a>
	<ul>
		{{#each materials.components.items}}
		<li>
			<a href="components.html#{{@key}}">{{name}}</a>
		</li>
		{{/each}}
	</ul>
</li>

<li>
	<a href="cards.html" class="f-menu__heading">Cards</a>
	<ul>
		{{#each materials.cards.items}}
		<li>
			<a href="cards.html#{{@key}}">{{name}}</a>
		</li>
		{{/each}}
	</ul>
</li>
```


When you run `$ npm  start` it compiles everything in `src` and dumps the artifacts in `dist`. 

`dist` is the folder that is served up to http://localhost:3000. You can look in that folder to see what the build is outputting and what you can hit in a browser when the server is running.

**Comment by herince** [comment]
I know most of the things you just explained to me. I'm just not very familiar with JS templating for now...

Your documentation is pretty good, tho. After rereading it and looking up a few more articles on handlebars templating, I think I can fix what I wanted to.

Thanx! (the problem was that the project I'm working on got very big and I needed the "grouped materials" feature) The toolkit you did is pretty awesome... I did look up many styleguide generators before choosing fabricator... GJ! :)

**Comment by mattboy115** [comment]
I am having a Cannot GET error as well. It was working just fine when I first built the project. But when I stopped the Localhost3000 and came back to it with npm start and a lot of things come back with "Cannot GET" like my structures. The structures folder in src and all the html files I made are still there but they won't display in the Localhost3000. Also they're not showing up in the dist folder. I've heard you have to edit the gulp file to fix this but I wouldn't know where to start in editing it. I'm still very much a beginner.
