### ISSUE TITLE
Add css also to the styleguide output (maybe also js?)

### ISSUE THREAD

**Issue by boehmatron** [fbrctr/fabricator#131]
I think it would be very useful to **show the CSS formatting additionally** to the existing HTML output for every component/structure.
There might also be cases where the according javascript would be helpful.
I would love to see this in the future — fabricator is awesome =D

**Comment by herince** [comment]
+ 1

**Comment by boehmatron** [comment]
Is there a realistic chance for this feature ?

**Comment by tonifisler** [comment]
I don't see the point of such a feature. Why would you need to see the CSS styles? That is not what styleguides are supposed to be for...

**Comment by boehmatron** [comment]
the opinion on what styleguides are made for may differ where and how they are used. 
If you take a big corporate enterprise that has one CD/CI department that defines one online styleguide and has to deliver that styleguide to a lot of different internal departments, agencies or other external suppliers, you often can not use one single css file but what to have one place where you always can reference and point developers/designers to, so that they can copy the html/css/js they need.

Looking and these big companies (and there are a lot of them, like banks, telcos,..) it really makes sense.
I would love to use fabricator internally if it would be possible to add the css. or maybe there is a way to make it modular, and add different sections to one style definition,.. like css, like javascript,.. like (whatever)...

Do you see my point?

**Comment by larrybotha** [comment]
This looks like an opportunity to consider some way of using plugins with fabricator. Not everyone would necessarily want this, but it would be beneficial to some.

I've added a bunch of features to [our own fabricator](https://github.com/fixate/fixate-fabricator) which is quite specific to how we setup our styleguides, but some of these features would be super useful to some. An opt in via plugins would be great to avoid bloat on the main project.

Plugins could be installed via bower / npm, and perhaps switching a flag in a config.

What's great about fabricator right now is that it's so small, and so flexible; a plugin architecture would be an excellent step forward in retaining this simplicity, while allowing for on-demand extension / features.

**Comment by boehmatron** [comment]
Sounds great to me Larry,... and I would absolutely support it :)

2015-07-10 11:39 GMT+02:00 Larry Botha <notifications@github.com>:

**Comment by larrybotha** [comment]
My node-fu is not 3rd Dan yet, but this is something I'd like to look into when I get a minute - I've used KSS, and SourceJS, and they don't scratch the surface of how much Fabricator has sped up my workflow, so this will be a huge benefit to me, too.

Perhaps this will give someone else the inspiration to get it going, or begin a discussion, too :)

**Comment by LukeAskew** [comment]
Plugin architecture is a great idea. It's something I've heard since the beginning of the project.

I'm of the same opinion as @tonifisler - I don't see the usefulness of adding CSS, but I also really like giving people flexibility. 

Let me think about this one.

**Comment by boehmatron** [comment]
Cool stuff,...

Just for my interest: hier do you manage the css styles so that devs and designers can see what the definition is exactly. For example if it comes to a specific font or color.
I see fabricator very useful and mighty with a lot potential beyond the usefulness of developers, and I would love to see and use it :)

**Comment by larrybotha** [comment]
First of all you'll obviously need the classes defined somewhere.

In Fixate's fabricator I `@import` the production styles straight into the fabricator styles (https://github.com/fixate/fixate-fabricator/blob/master/src/assets/fabricator/styles/fabricator.scss#L25), because we make heavy use of placeholders (%my-class). 

Now, if we don't have a class explicitly set in production styles, then we can create those in specific fabricator stylesheets.

We have a layout view responsible for showing how font size and colour modifiers look. This view's styles are also `@import`ed into fabrictor.scss, but above production styles: https://github.com/fixate/fixate-fabricator/blob/master/src/assets/fabricator/styles/fabricator.scss#L15.

You can pair the typography view with its own fabricator _typography.scss in the same way. Here you can add or define your own classes to extend or add styles only to fabricator (our [_layout.scss](https://github.com/fixate/fixate-fabricator/blob/master/src/assets/fabricator/styles/views/_layout.scss) illustrates this - don't mistake it for fabricator's _layout.scss).

e.g.
``` scss
# prod _typography.scss:
// we use a modified BEM syntax for full HTML comment compatibility with class names
// font colour modifiers
%fc_-primary {...} 
%fc_-secondary {...}
%fc_-tertiary {...}


# views/_typography.scss
.fc_-primary { @extend %fc_-primary;} 
.fc_-secondary { @extend %fc_-secondary;}
.fc_-tertiary { @extend %fc_-tertiary;}
```

And then in [`data/typography.yml`](https://github.com/fixate/fixate-fabricator/blob/master/src/data/typographic-modifiers.yml):

```yml
colours:
  - primary
  - secondary
  - tertiary
```

In my [typography/font-colors.html](https://github.com/fixate/fixate-fabricator/blob/master/src/materials/typographic-modifiers/font-colors.html) material I'll then loop over the data in the yml to generate the full classes for my fonts, and apply them to some typographic element (e.g. `<p class="fc_-{{this}}>lorem</p>`). I do this for pretty much every modifier I have - font colours, backgrounds, font faces, font sizes, wraps, islands, even padding and margin modifiers.

This isn't _exactly_ how our fabricator is setup, but this will give you a good idea on how can go about achieving a flexible and informative styleguide.

Fork our repo: https://github.com/fixate/fixate-fabricator (you'll likely have to change a few paths here and there - you won't have style.scss where our fabricator looks) and you'll see how everything comes together, or just have a look around.

I also added a script which dynamically gets [hex](https://github.com/fixate/fixate-fabricator/blob/master/src/assets/fabricator/scripts/utils/color-block.js) and [font size values](https://github.com/fixate/fixate-fabricator/blob/master/src/assets/fabricator/scripts/utils/computed-style.js), too. No more referring to your Sass or design for any of those values - fabricator does it for you.

The important thing to remember here is that fabricator is the module handling all the dirty work, and is a dependency on the entire front end where you're free to tinker as you want. This means that you can do pretty much as you please :D 

This project continues to blow my mind on a daily basis. There is no alternative to fabricator, and we can only make it better O.o
