### ISSUE TITLE
Any recommendations for structuring toolkits that use web component frameworks like angular, react or polymer?

### ISSUE THREAD

**Issue by ichabodcole** [fbrctr/fabricator#137]
Are there any examples of using this tool with frameworks like angular / react / polymer / etc. My applications tend to be built in a very componentized fashion where each component is a folder that contains a js file, scss/css file, and potentially a template file that works together to create the final interactive component/widget, which might be instantiated via a custom dom tag. It seems like the component itself would live outside of the materials folder, and then the materials folder would just have an html file and maybe some bootstrapping code to setup the component.

Any thoughts, experience, or examples are greatly appreciated.

**Comment by LukeAskew** [comment]
No examples currently. 

I created the project initial with strict framework/backend agnosticism in mind (much like Bootstrap or Foundation). My mindset with toolkits is that it should be a drop-in UI in to any number of applications. 

Building a toolkit around a certain view layer (like React, Angular, Razor, Erb) reduces it's reusability. I understand that not every project needs to have this level of decoupling, but that was my need when I built Fabricator initially, so much of it's architecture forces that constraint.

**Comment by bbodine1** [comment]
We use fabricator so that I (Frontend Developer) can develop a website in tandem with the backend team and the angular team. Ultimately what I create gets imported into an angular website. The angular website is the production. The css is pulled in through node packages but the html is manually copied to the angular templates where the required ng-stuff directives are added where they are needed to make angular function correctly.

**Comment by qaidj** [comment]
@bbodine1 - can you describe a bit more how the css is pulled into the angular project through node packages?

I'm currently building a Fabricator instance along side and in support of an Ember project. I've structured things so that Fabricator's styles are a subtree repo that can be consumed by (and also updated from) the Ember project. It works well enough, but it's not as elegant a solution as I'd prefer. Interested in your approach with Angular and node packages.

**Comment by ptibbetts** [comment]
@bbodine1 @qaid I'd love to see either of your implementations if you could share a link?

**Comment by qaid** [comment]
@ptibbetts the project I've built with Fabricator is an internal document at the moment. But are there specific questions you might have about the way I set it up?
