### ISSUE TITLE
commenting system

### ISSUE THREAD

**Issue by Idrus82** [fbrctr/fabricator#141]
Hi there,

I just start using Fabricator to build style guide documentation on my new project and it is great tool!.

BTW, I just wondering if it has commenting system? so when we build it, the team members could add comment on the view page and the others members could see the comment or even reply it.

might be it just like adding disqus or livefyre on this tool... I think it would be great feature.

Thanks for the great tools :+1:

**Comment by LukeAskew** [comment]
That sounds like a really useful feature.

I've used a handful of prototype commenting apps like Notable and Invision. I wonder if there is something out there that could integrate nicely into Fabricator.

This feature's a bit tough to integrate completely into the project because the lack of database and server-side dependencies is a *feature* - Fabricator is meant to be very portable.

Thanks for opening this issue. You've got my wheels turning!

**Comment by Idrus82** [comment]
yeah..you're right with the database dependencies.

I just wondering if we could integrate like SideComments.js https://github.com/aroc/side-comments in the future, but i'm not sure how to store it in database. :smile: 

currently we integrate Disqus in our project. please see the image below.
![sample](https://cloud.githubusercontent.com/assets/10343502/8365654/172ad50c-1bc1-11e5-81fa-40063c2f8930.png)

it is a bit tricky to make each material has a comment box; but achievable. currently it is being tested.

BTW, Thank for your prompt feedback. :+1:
