### ISSUE TITLE
Timeline of a material / document: appending Git commit messages to notes section

### ISSUE THREAD

**Issue by qaidj** [fbrctr/fabricator#171]
My needs:
 
1. give temporal context to the thing being viewed (how long ago it was changed)
1. show what was changed during the thing's last change (ie the exact thing you say in your Git commit message).

My thinking is that I need a way to append Git commits to the notes section of something being modified (when it has the notes display capability). This way I don't have to create an additional workflow which duplicates the things I've already expressed in a Git commit.

Any ideas on how I might achieve this? Maybe a hook that listens for new git commits, and appends the message text to the specified document? 

😷 Bleh. Feels messy as I type it. But I dunno.

**Comment by LukeAskew** [comment]
This is a tough one. I've heard this request before (#51), but I'm not convinced it fits in the scope of this project because it assumes a lot about how a team works.

The best I can offer is an example of what's worked well for my teams. Its a more traditional approach:

- Use semver to manage versioning of your toolkit
- Create a `changelog.html` and `changelog/` dir (similar to `docs`) that are just markdown docs with Changelog information for each release. End-users can read those docs and compare their version against the current version.

**Comment by qaidj** [comment]
Thanks for the suggestion!
