### ISSUE TITLE
Query, does Fabricator parse comments in scss/css 

### ISSUE THREAD

**Issue by vidhill** [fbrctr/fabricator#235]
First off compliments on what looks like a very nice project, 

my question, does Fabricator parse comments in scss/css?

If not has anyone used node-kss or DSS to populate the materials data

**Comment by jonorherrington** [comment]
What's the use case you are using this for @vidhill? At the moment the scss and css don't appear under the notes section (i know this has been another feature requested in previous issues). Since that isn't a feature yet, is there a reason you are trying to parse comments in scss/css instead of just using the YAML/Markdown combo?

**Comment by vidhill** [comment]
I like the concept of writing the docs as close to the source code as possible, as is the convention with javascript documentation. (jsDocs, dGeni)

Example KSS Comment syntax
```
// Button
//
// Your standard button suitable for clicking.
//
// :hover   - Highlights when hovering.
// .shiny   - Do not press this big, shiny, red button.
//
// Markup: button.html
//
// Style guide: components.button
.button {
  ...
}
.button.shiny {
  ...
}
````

**Comment by LukeAskew** [comment]
We don't currently do this, but I could see this as a future enhancement or plugin.
